-- ===============================
-- = INITIALISATION DE LA BASE
-- ===============================

-- Activation de l'extension PostGIS
CREATE EXTENSION IF NOT EXISTS postgis;

-- Création des tables
CREATE TABLE IF NOT EXISTS roles(
   id INTEGER GENERATED BY DEFAULT AS IDENTITY,
   nom VARCHAR(50) NOT NULL,
   synchro BOOLEAN NOT NULL DEFAULT false,
   PRIMARY KEY(id),
   UNIQUE(nom)
);

CREATE TABLE IF NOT EXISTS entreprises(
   id INTEGER GENERATED BY DEFAULT AS IDENTITY,
   nom VARCHAR(255) NOT NULL,
   synchro BOOLEAN NOT NULL DEFAULT false,
   PRIMARY KEY(id),
   UNIQUE(nom)
);

CREATE TABLE IF NOT EXISTS statuts_avancement(
   id INTEGER GENERATED BY DEFAULT AS IDENTITY,
   nom VARCHAR(50) NOT NULL,
   valeur INTEGER NOT NULL,
   synchro BOOLEAN NOT NULL DEFAULT false,
   PRIMARY KEY(id),
   UNIQUE(nom),
   UNIQUE(valeur)
);

CREATE TABLE IF NOT EXISTS parametres(
   id INTEGER GENERATED BY DEFAULT AS IDENTITY,
   nb_tentatives_connexion INTEGER NOT NULL DEFAULT 3,
   duree_session INTEGER NOT NULL DEFAULT 3600,
   synchro BOOLEAN NOT NULL DEFAULT false,
   PRIMARY KEY(id)
);

CREATE TABLE IF NOT EXISTS utilisateurs(
   id INTEGER GENERATED BY DEFAULT AS IDENTITY,
   email VARCHAR(255) NOT NULL,
   password VARCHAR(255) NOT NULL,
   synchro BOOLEAN NOT NULL DEFAULT false,
   id_role INTEGER NOT NULL,
   PRIMARY KEY(id),
   UNIQUE(email),
   FOREIGN KEY(id_role) REFERENCES roles(id)
);

CREATE TABLE IF NOT EXISTS utilisateurs_bloques(
   id INTEGER GENERATED BY DEFAULT AS IDENTITY,
   date_blocage TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
   synchro BOOLEAN NOT NULL DEFAULT false,
   id_utilisateur INTEGER NOT NULL,
   PRIMARY KEY(id),
   FOREIGN KEY(id_utilisateur) REFERENCES utilisateurs(id)
);

CREATE TABLE IF NOT EXISTS signalements_niveaux(
   id INTEGER GENERATED BY DEFAULT AS IDENTITY,
   libelles VARCHAR(20),
   prix_m2 FLOAT NOT NULL DEFAULT 0,
   synchro BOOLEAN NOT NULL DEFAULT false,
   PRIMARY KEY(id)
);

CREATE TABLE IF NOT EXISTS signalements(
   id INTEGER GENERATED BY DEFAULT AS IDENTITY,
   date_creation VARCHAR(50) NOT NULL,
   surface DOUBLE PRECISION NOT NULL,
   budget FLOAT DEFAULT 0,
   localisation GEOGRAPHY NOT NULL,
   synchro BOOLEAN NOT NULL DEFAULT false,
   id_utilisateur_createur INTEGER NOT NULL,
   id_entreprise INTEGER DEFAULT NULL,
   id_niveaux INTEGER DEFAULT NULL,
   PRIMARY KEY(id),
   FOREIGN KEY(id_utilisateur_createur) REFERENCES utilisateurs(id),
   FOREIGN KEY(id_entreprise) REFERENCES entreprises(id),
   FOREIGN KEY(id_niveaux) REFERENCES signalements_niveaux(id)
);

CREATE TABLE IF NOT EXISTS avancements_signalement(
   id INTEGER GENERATED BY DEFAULT AS IDENTITY,
   date_modification TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
   synchro BOOLEAN NOT NULL DEFAULT false,
   id_utilisateur INTEGER NOT NULL,
   id_statut_avancement INTEGER NOT NULL,
   id_signalement INTEGER NOT NULL,
   PRIMARY KEY(id),
   FOREIGN KEY(id_utilisateur) REFERENCES utilisateurs(id),
   FOREIGN KEY(id_statut_avancement) REFERENCES statuts_avancement(id),
   FOREIGN KEY(id_signalement) REFERENCES signalements(id)
);


CREATE TABLE IF NOT EXISTS signalements_photos(
   id INTEGER GENERATED BY DEFAULT AS IDENTITY,
   path_photo VARCHAR(255) NOT NULL UNIQUE,
   synchro BOOLEAN NOT NULL DEFAULT false,
   id_signalement INTEGER NOT NULL,
   date_creation TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
   PRIMARY KEY(id),
   FOREIGN KEY(id_signalement) REFERENCES signalements(id)
);


-- Création d'index pour les performances
CREATE INDEX IF NOT EXISTS idx_utilisateur_email ON utilisateurs(email);
CREATE INDEX IF NOT EXISTS idx_signalement_localisation ON signalements USING GIST(localisation);
CREATE INDEX IF NOT EXISTS idx_signalement_entreprise ON signalements(id_entreprise);
CREATE INDEX IF NOT EXISTS idx_signalement_createur ON signalements(id_utilisateur_createur);
CREATE INDEX IF NOT EXISTS idx_avancement_signalement ON avancements_signalement(id_signalement);

-- Affichage de confirmation
DO $$
BEGIN
    RAISE NOTICE 'Schéma de base de données initialisé avec succès';
END $$;
